---
- name: Add repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    gpgcheck: no

- name: install epel 
  yum: name={{ item }} state=installed
  with_items:
    - socat

- block:
  
  - name: install erlang el6
    yum: 
      name: http://www.rabbitmq.com/releases/erlang/erlang-18.3.4.4-1.el6.x86_64.rpm
      #name: http://www.rabbitmq.com/releases/erlang/erlang-18.3.4-1.el6.x86_64.rpm
      #name: http://www.rabbitmq.com/releases/erlang/erlang-17.4-1.el6.x86_64.rpm
      state: present       
  - name: install rabbitmq-server el6
    yum:
      name: http://www.rabbitmq.com/releases/rabbitmq-server/v3.6.5/rabbitmq-server-3.6.5-1.noarch.rpm
      #name: http://www.rabbitmq.com/releases/rabbitmq-server/v3.5.7/rabbitmq-server-3.5.7-1.noarch.rpm
      state: present
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "6"
      
- block:

  - name: install erlang el7
    yum:
      #name: http://www.rabbitmq.com/releases/erlang/erlang-19.0.4-1.el7.centos.x86_64.rpm
      name: http://www.rabbitmq.com/releases/erlang/erlang-18.3.4.4-1.el7.centos.x86_64.rpm
      state: present 
  - name: install rabbitmq-server el7
    yum:
      #name: http://www.rabbitmq.com/releases/rabbitmq-server/v3.6.15/rabbitmq-server-3.6.15-1.el7.noarch.rpm
      name: http://www.rabbitmq.com/releases/rabbitmq-server/v3.6.5/rabbitmq-server-3.6.5-1.noarch.rpm
      state: present
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"
  
- name: enable_plugin
  shell: rabbitmq-plugins enable rabbitmq_management && rabbitmq-plugins list
  
- name: create rmq datadir 
  file: state=directory path={{ rmq_data_basedir }} owner=rabbitmq group=rabbitmq
  
- name: unarchive_war_file
  unarchive: 
    src: ssl.tar.gz
    dest: "{{ rmq_basedir }}"
    
- name: configure_rmq_conf
  template: 
   src: rabbitmq.config.j2 
   dest: "{{ rmq_confdir }}/rabbitmq.config"
- name: configure_rmq_env
  template: 
    src: rabbitmq-env.conf.j2 
    dest: "{{ rmq_confdir }}/rabbitmq-env.conf" 
  notify: 
    - restart rmq
- name: start rmq
  service: name=rabbitmq-server state=started


- name: add rmq user privileges
  rabbitmq_user:
    user: "{{ rmq_user }}"
    password: "{{ rmq_pass }}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
  when: "NEW_INSTALL is defined and NEW_INSTALL == 'yes'"

- name: add privileges
  shell: rabbitmqctl set_user_tags {{ rmq_user }} management
  when: "NEW_INSTALL is defined and NEW_INSTALL == 'yes'"
