---
- block:
  - name: install percona repos
    yum: 
      name: http://www.percona.com/downloads/percona-release/redhat/0.1-6/percona-release-0.1-6.noarch.rpm
      state: present
    
  - name: install_mysql
    yum: name={{ item }} state=present
    with_items:
      - Percona-Server-server-56
      - Percona-Server-devel-56 
      - MySQL-python
      
  - name: start_mysql
    service: name=mysql state=started enabled=yes
  
  - name: install_namedmanager-www
    yum:
      name: https://repos.jethrocarr.com/pub/amberdms/linux/centos/6/amberdms-custom/x86_64/namedmanager-www-1.9.0-3.el6.noarch.rpm
      state: present
      validate_certs: no
  
  - name: install_namedmanager-www
    yum:
      name: https://repos.jethrocarr.com/pub/amberdms/linux/centos/6/amberdms-custom/x86_64/namedmanager-bind-1.9.0-3.el6.noarch.rpm
      state: present
      validate_certs: no 
  
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "6"
      
- block:
  - name: install_mysql centos7
    yum: name={{ item }} state=present
    with_items:
      - mariadb
      - mariadb-server
      - mariadb-devel 
      - MySQL-python
  
  - name: start_mysql centos7
    systemd: name=mysqld state=started enabled=yes
  
  - name: install_namedmanager-www
    yum:
      name: https://repos.jethrocarr.com/pub/amberdms/linux/centos/7/jethrocarr-custom/x86_64/namedmanager-www-1.9.0-2.el7.centos.noarch.rpm
      state: present
  
  - name: install_namedmanager-www centos7
    yum:
      name: https://repos.jethrocarr.com/pub/amberdms/linux/centos/7/jethrocarr-custom/x86_64/namedmanager-bind-1.9.0-2.el7.centos.noarch.rpm
      state: present
      
  when:
      - ansible_distribution == "CentOS"
      - ansible_distribution_major_version == "7"
  
- name: set_mysql_root_pw
  shell: mysqladmin -uroot password '{{ mysql_root_pass }}'
  
- name: create_db_name
  mysql_db:
    login_host: "127.0.0.1"
    login_user: "root"
    login_password: "{{ mysql_root_pass }}"
    login_port: "3306"
    name: "{{ db_name_namedmanager }}"
    encoding: "utf8"
    state: "present"

- name: create_db_user
  mysql_user:
    login_host: "127.0.0.1"
    login_user: "root"
    login_password: "{{ mysql_root_pass }}"
    login_port: "3306"
    name: "{{ db_name_namedmanager }}"
    password: "{{ db_pass_namedmanager }}"
    host: "localhost"
    priv: "*.*:all"
    state: "present"

- name: copy_namedmanager_sql
  copy:
    src: namedmanager.20180421.sql.gz
    dest: "{{ pack_dir }}/namedmanager.sql.gz"
    
- name: import_dbsql
  mysql_db:
    login_host: "127.0.0.1"
    login_user: "root"
    login_password: "{{ mysql_root_pass }}"
    login_port: "3306"
    name: "{{ db_name_namedmanager }}"
    target: "{{ pack_dir }}/namedmanager.sql.gz"
    state: "import"

  
- name: create_named_logs_dir 
  file: state=directory path=/data/named/logs owner=named group=named
   
- name: unarchive_zh_patch
  unarchive: 
    src: namedmanager_zh_patch.tar.gz
    dest: /usr/share
    
- name: namedmanager_www_cfg
  template: 
    src:  config.php.j2
    dest: "{{ namedmanager_conf_dir }}/config.php"
  notify:
    - restart_httpd
    
- name: namedmanager_bind_cfg
  template: 
    src: config-bind.php.j2 
    dest: "{{ namedmanager_conf_dir }}/config-bind.php"  
#  notify:
#    - restart_named
- name: rsync_named_conf
  copy:
    src: named.conf
    dest: /etc/named.conf
    owner: named
    group: named
  notify:
    - restart_named
